# Do not use this configuration in production.
# It is for demonstration purposes only.
scrape_configs:
  - job_name: "default"
    scrape_interval: "15s"

    static_configs:
      - targets: ["dotnet-monitor-pprof-api:5063"]

    profiling_config:
      pprof_config:
        memory:
          enabled: false
        block:
          enabled: false
        goroutine:
          enabled: false
        mutex:
          enabled: false
